### ISSUE TITLE
for repl.it pls

### ISSUE THREAD

**Issue by PcallHub** [levno-710/Prometheus#101]
**Describe the bug**

**Expected behavior**

**To Reproduce**

If your problem is a non-working obfuscated file, please also include a minimal source code example, your config file as well as the output file that you got.

**Screenshots**

**Additional context**

**Comment by Brohammer5** [comment]
Incorrect Usage of the Bug Form. I don't think he plans on make it replit friendly. You should just hop into a different ide such as zerobrane or the windows exe to use it.
