### ISSUE TITLE
[BUG] Doesn't launch

### ISSUE THREAD

**Issue by yanNotDev** [levno-710/Prometheus#14]
**Describe the bug**
Upon running `lua ./cli.lua --preset Strong ./test.lua` i get the following output
```
lua: ./src/obfuscator/util.lua:7: module 'bit' not found:
	no field package.preload['bit']
	no file './src/bit.lua'
	no file './src/bit.lua'
	no file './bit.lua'
	no file '/usr/share/lua/5.4/bit.lua'
	no file '/usr/share/lua/5.4/bit/init.lua'
	no file '/usr/lib/lua/5.4/bit.lua'
	no file '/usr/lib/lua/5.4/bit/init.lua'
	no file './bit.lua'
	no file './bit/init.lua'
	no file '/usr/lib/lua/5.4/bit.so'
	no file '/usr/lib/lua/5.4/loadall.so'
	no file './bit.so'
stack traceback:
	[C]: in function 'require'
	./src/obfuscator/util.lua:7: in main chunk
	[C]: in function 'require'
	./src/obfuscator/enums.lua:8: in main chunk
	[C]: in function 'require'
	./src/obfuscator/pipeline.lua:10: in main chunk
	[C]: in function 'require'
	./src/prometheus.lua:16: in main chunk
	[C]: in function 'require'
	./src/cli.lua:13: in main chunk
	[C]: in function 'require'
	./cli.lua:12: in main chunk
	[C]: in ?
```

**Expected behavior**
The file was supposed to run properly

**To Reproduce**
Have an arch system with the following lua-related packages installed:
lua 5.4.3-1
lua51 5.1.5-9
lua52 5.2.4-5
lua53 5.3.6-1
luajit 2.0.5-3
luarocks 3.8.0-1

git clone the repo, cd into it, and do `lua ./cli.lua --preset Strong ./test.lua`

**Comment by tornadia** [comment]
Solution:
- Install `liblua5.2` deps and `lua5.2`.
- Install [LuaRocks](https://luarocks.org/) for lua5.2
  - instead of `./configure`, use `./configure --lua-version=5.2`
```bash
wget https://luarocks.org/releases/luarocks-3.8.0.tar.gz
tar zxpf luarocks-3.8.0.tar.gz
cd luarocks-3.8.0
./configure --lua-version=5.2 && make && sudo make install
sudo luarocks install luasocket
lua
Lua 5.3.5 Copyright (C) 1994-2018 Lua.org, PUC-Rio
> require "socket"
```
  - make sure to install any required deps if run into issues
- Install the dependency [lua-bit-numberlua](https://github.com/davidm/lua-bit-numberlua)
  - not sure if package is available anymore through luarocks. install manually.
 ```bash
DOWNLOAD/INSTALLATION
  If using LuaRocks:
    luarocks install lua-bit-numberlua
  Otherwise, download <https://github.com/davidm/lua-bit-numberlua/zipball/master>.
  Alternately, if using git:
    git clone git://github.com/davidm/lua-bit-numberlua.git
    cd lua-bit-numberlua
  Optionally unpack:
    ./util.mk
  or unpack and install in LuaRocks:
    ./util.mk install 
```
- [Clone this repo](https://levno-710.gitbook.io/prometheus/getting-started/installation) and have fun.
  - may have to change `require 'bit'` to `require 'bit.numberlua'`

**Comment by levno-710** [comment]
# Fixed
The Problem was, that a package was required, that is not present on every system.
I changed
```lua
local bit32 = require("bit");
```
to
```lua
local bit32 = require("prometheus.bit").bit32;
```
