### ISSUE TITLE
Prometheus will not properly use the Strong preset

### ISSUE THREAD

**Issue by Apachedrag427** [levno-710/Prometheus#16]
When I try to use the --preset Strong, it returns me with this output and provides no file:
![image](https://user-images.githubusercontent.com/93100547/149667139-fa9dc5fb-9669-4797-8061-b569da3f26df.png)
I'm not sure what may be causing this to happen, it worked fine before and the Medium and Weak presets work fine

**Comment by levno-710** [comment]
Could you please provide the lua file you tried to obfuscate. This seems to be a bug in the custom bytecode compiler.
The reason why Medium and Weak work, is that they don't compile your program to custom bytecode, but only apply source code obfuscation.

Are you using the windows build or the lua sources?
You could try to use the lua sources to run prometheus.

**Comment by Apachedrag427** [comment]
> Could you please provide the lua file you tried to obfuscate.
[lua.txt](https://github.com/levno-710/Prometheus/files/7905958/lua.txt)  (I had to change it to .txt to upload)

> Are you using the windows build or the lua sources?
I'm using the windows build, prometheus.exe

> Also did you download a newer version or did this happen without any obvious reason?
I didn't upgrade version, I just tried it with a different lua file and it worked fine

Also, sidenote, this uses apis and the environment of [a computer mod in minecraft](https://tweaked.cc/)

**Comment by levno-710** [comment]
# Fixed
This bug is now fixed. I suggest you download the newest release of prometheus in order to obfuscate your file.

There was an issue, where break statements could only be compiled within while loops. Because your file contains break multiple break statements inside of for loops, prometheus failed to obfuscate it and crashed.
