### ISSUE TITLE
[Suggestion] Support Lua in gamesense

### ISSUE THREAD

**Issue by DotRacel** [levno-710/Prometheus#20]
gamesense is a cheat for CSGO, provides LuaJIT(+ Lua 5.1) lua enviroment, but supports unicodes in variable name
renamer with unicode support will be pretty confusing

**Comment by levno-710** [comment]
The problem with this is, that the Lexer cannot handle Unicode chars without a complete rewrite.
While it would be possible to generate names using uniode chars. Prometheus would not be abled to parse these files.
