### ISSUE TITLE
[BUG] Random table keys can conflict with Lua keywords

### ISSUE THREAD

**Issue by brandonsturgeon** [levno-710/Prometheus#26]
**Describe the bug**
I've seen a few situations where the random two-character table key will result in "do", "or", "if", "in". - which of course causes an error. The chance of this happening goes up as the input gets larger.

**Expected behavior**
Generated code should be valid Lua

**To Reproduce**
Have poor luck I guess?

**Screenshots**
![image](https://user-images.githubusercontent.com/7936439/154016971-ed42766d-22f3-4086-a2a0-3e3ade88985d.png)

**Comment by levno-710** [comment]
I fixed this issue, but the fix is not yet included in the current release. It will be included in the next release
