### ISSUE TITLE
ProxifyLocals Combined with Vmify creates peformance issues

### ISSUE THREAD

**Issue by wrefgtzweve** [levno-710/Prometheus#29]
**Describe the bug**
I've noticed that performance drops significantly when im using the Strong preset, after trying out a lot of stuff i've noticed that VM and Proxify run fine on their own but get very bad when combined. I'm using Garry's mod lua enviroment for this.

The code im using to test:
```lua
local SysTime = SysTime
local Distance = FindMetaTable("Vector").Distance

local vec1 = Vector(1, 2, 3)
local vec2 = Vector(13, 26, -10)

local count = 10000

local StartTime = SysTime()

for i = 1, count do
	-- Repeat an action 10,000 times to check how long it takes on average
	-- Example action:
	Distance(vec1 , vec2)
end

local EndTime = SysTime()
local TotalTime = EndTime - StartTime
local AverageTime = TotalTime / count

print("Custom Total: " .. TotalTime .. " seconds. Average: " .. AverageTime .. " seconds.")

```
![image](https://user-images.githubusercontent.com/69946827/154870300-a7dbe579-0622-488f-a892-0f2f9677d7ee.png)
As you can see here, strong significantly increases the time it takes for the benchmark to run. 
![image](https://user-images.githubusercontent.com/69946827/154870365-ca7ed335-a9f8-4a76-a48a-2b365810b90d.png)
In this screenshot i compare it to my custom preset which is basically Strong without using proxify locals
![image](https://user-images.githubusercontent.com/69946827/154870386-f6e7acce-98af-42e7-8a64-de5aa767abd2.png)

And for reference, this is Strong without VM and with proxify:
![image](https://user-images.githubusercontent.com/69946827/154870412-dd01b295-81b3-4607-8215-75f797536035.png)
![image](https://user-images.githubusercontent.com/69946827/154870421-db8664b9-c4e8-4153-891f-5af34dc95cae.png)

**Expected behavior**
Some way of using both of these methods at the same time without having peformance issues.

**To Reproduce**
As described before, any configuration that uses both VM and Proxify together will create a massive peformance sink.

**Screenshots**
See main explanation.

**Additional context**
Gmod lua wiki: https://wiki.facepunch.com/gmod/ Garry's mod uses Lua 5.1

**Comment by Brohammer5** [comment]
As stated by the developer, "the VM is currently extremely slow and I am in the moment working on a better vm to increase speed. Another problem that the new vm in the next release will fix, is that it is relatively easy to dump constants used by the old vm."
Link to Comment:
https://github.com/levno-710/Prometheus/discussions/28#discussioncomment-2211572

**Comment by wrefgtzweve** [comment]
As can be seen in this example:
![image](https://user-images.githubusercontent.com/69946827/154935621-dd7ccce2-2cc5-4e29-b792-07401e817c59.png)

VM by itself isn't currently slowing stuff down, when used together with proxylocals it starts to cause peformance issues.

**Comment by levno-710** [comment]
Proxify locals is relatively slow, because it uses metatablea a lot. However, it becomes slower, the more local variables your program has. The VM adds a lot of local variables, so that the slowdowns combined are very big

**Comment by brandonsturgeon** [comment]
> Proxify locals is relatively slow, because it uses metatablea a lot. However, it becomes slower, the more local variables your program has. The VM adds a lot of local variables, so that the slowdowns combined are very big

Is that something that could potentially be remedied?
