### ISSUE TITLE
[BUG] Parsing error when there is no leading 0 before the decimal point

### ISSUE THREAD

**Issue by zebranine** [levno-710/Prometheus#39]
Thanks for all your hard work on this, very promising.

Unfortunately I see a parsing error when there is no leading 0 before the decimal point, so:

```lua
local val = .5
```

results in output:

`←[0m←[31mPROMETHEUS: Parsing Error at Position 1:12, Unexpected Token ".". Expected a Expression!←[0m
`

whereas this generates without issue:

```lua
local val = 0.5
```

I have seen a similar situation in other minifiers/obfuscators where the absence of a number _after_ the decimal point prevents generation (not the case here).

- Lua version: lua-5.1.5 Win64
- Command line: `lua5.1.exe cli.lua --preset Medium test.lua`
- Tested with various presets

**Comment by levno-710** [comment]
Thanks for reporting this bug,
I fill fix it asap

**Comment by levno-710** [comment]
# Update
This issue is fixed in the development version now.
See: https://github.com/levno-710/Prometheus/commit/7a35326d9d2b9130ee70bdaa5b33266f90456079
