### ISSUE TITLE
Minifier mishandles empty key table access

### ISSUE THREAD

**Issue by dragonbane0** [levno-710/Prometheus#44]
**Describe the bug**
I currently can not use Prometheus at all since even the Minify step produces compile time errors. This is because the game engine I'm writing lua for, has the notable quirk of storing a lot of userdata objects in tables with a 0 length key which I need to access.

This will look like this for an engine call:
`CppCall(QDScript.GC_MESH[""] , "SetVisible" , true , targetObject)`

Prometheus will turn this line into:
`CppCall(QDScript.GC_MESH. , "SetVisible" , true , X)`

`GC_MESH.` obviously is not a valid access anymore, while `GC_MESH[""]` is.

**Expected behavior**
I guess that the Minifier handles this scenario and leave the access as is.

---
Help is very appreciated. Thanks for providing an open source obfuscator!

**Comment by levno-710** [comment]
Thanks for reporting this issue.
The bug is fixed with https://github.com/levno-710/Prometheus/commit/ddc3b872cdb1f7d7e58655cb575bb7f61b1f9db4
However, because other parts of the development branch are not finished yet, I cannot publish a new release.
If you want to use prometheus for your project, you should add that modification to your local copy.

**Comment by dragonbane0** [comment]
Thanks for the quick response!

Now I get the following error during execution of Prometheus instead:
`The Prefix "" is not a valid Identifier in LuaU`

Going in and switching the version of the Pipeline to Lua51 does not seem to change the result either

**Comment by levno-710** [comment]
This should be fixed by https://github.com/levno-710/Prometheus/commit/a0f7cda7c250b12486d88d3a86be8c31c6b21f80

**Comment by dragonbane0** [comment]
Excellent. Can confirm this fixes it. The minifier now produces a version of the script that compiles and runs without issues.
Wondering if this also causes issues for other popular obfuscators, cause they also produced non working scripts, but they are not open source so yeah.

There is another issue where enabling either Vmify, ProxifyLocals or both of them will make a singular function of my script fail for some reason while everything else works perfectly. But this is unrelated to this issue and I will attempt to hunt it down to the specific line later. 

For now I'm content with the minifier. Thank you for the quick fix!
