### ISSUE TITLE
prometheus.exe starting up then closing instantly +1 more

### ISSUE THREAD

**Issue by Fatalware** [levno-710/Prometheus#48]
Hey, I'm pretty new to this stuff and I don't really know what I'm doing, but these gyazo gifs should explain it.

https://gyazo.com/9d7cf61329ba6b736cfa06ae49b981c8

I tried replacing the lua53.dll with the latest one and tried running it with that and this happens

https://gyazo.com/2db09345ab8f901eee626f12d8a91bab

Is there anyway you could make like a tutorial or something?

**Comment by levno-710** [comment]
In the first video, the issue is that you don't run any commands. Prometheus does not have a UI, so it must be run from the command line, like you do in the second video. 
You can however not replace the dll, as different Lua versions behave differently.

**Comment by Fatalware** [comment]
[
![image](https://user-images.githubusercontent.com/104190748/164789525-0b8d1334-b922-4326-b5d1-a3fbe116fc22.png)
](url)

**Comment by Fatalware** [comment]
It's not clear in the image, but I got rid of the lua53.dll, and tried running it off of lua51.dll. The lua53.dll was the same one that came with the binaries you had me install, so I dunno what you meant by replacing the dll. (Just to clarify I only have the lua51.dll in the folder.

**Comment by levno-710** [comment]
Please open cmd instead of lua.exe and then paste the prometheus command

**Comment by Fatalware** [comment]
cmd as in the Windows Command prompt? That didn't work. Also sorry for wasting so much time.

**Comment by levno-710** [comment]
1. Open cmd.exe
2. type cd [Prometheus Directory]
3. Press Enter
4. Type prometheus.exe yourfile.lua
5. Press Enter

**Comment by Fatalware** [comment]
Thank you, it worked! 👍
