### ISSUE TITLE
attempt to call nil value newproxy

### ISSUE THREAD

**Issue by spik3n** [levno-710/Prometheus#49]
Issue with running a build .exe because of nil value in global newproxy

Error:
line 254: attempt to call a nil valie (global newproxy)

**Comment by levno-710** [comment]
It seems, that Prometheus was build using a Lua Version > 5.1
I added a fix for newer Lua Versions in https://github.com/levno-710/Prometheus/commit/cb8bb42f32ecbe1594c6c60396202db41eeb5db3
This will be included in Prometheus v0.2
