### ISSUE TITLE
[BUG] type(nil) is seemingly broken when obfuscating

### ISSUE THREAD

**Issue by dragonbane0** [levno-710/Prometheus#51]
**Describe the bug**
As mentioned in https://github.com/levno-710/Prometheus/issues/44, I finally tracked down the issue I was having with one of my script functions breaking as soon as Vmify, ProxifyLocals or both are used. Seems the issue is that type(nil) currently produces an error when used. So if you, for example, try to get the type of a table member that is nil, you get a non working script.

**Expected behavior**
type(nil) should be properly implemented when obfuscating.

**To Reproduce**
Adding a simple `local nilType = type(nil)` seems to break the function of my script immediately as soon as obfuscation options are used.

**Additional context**
Lua 5.1

**Comment by Brohammer5** [comment]
Try instead of using type(nil), try just nil or make the variable without value so by default it is nil

**Comment by dragonbane0** [comment]
Just nil doesn't produce any issues. For now I can work around it by simply checking if a variable is nil first before trying to check its type, but it's still a bug in the obfuscator right now, so it should be mentioned

**Comment by Brohammer5** [comment]
Issue seems to be around 340 when ( Beautified)while Obsfucated
This line of code
`(Pu .. "rpb")(B[string[(Gu / "A").l(-18003)]])`

**Comment by levno-710** [comment]
Fixed in upcoming version v0.2
