### ISSUE TITLE
[SUGGESTION] Option to disable watermark

### ISSUE THREAD

**Issue by wrefgtzweve** [levno-710/Prometheus#58]
Currently obfuscated code is shipped with the code below in front of it, I couldn't find a way to disable it through cli thus I'd like to suggest a cli option to disable this.  It's not a big deal, but most other obfuscators allow you to disable a text like this.
```lua
--[[
    Obfuscated using Prometheus Alpha v0.2 by levno-710
]]
```

**Comment by KhaledIsCool** [comment]
Why not just delete it yourself? It's not required.

**Comment by wrefgtzweve** [comment]
Yeah that's what I'm doing obviously, other obfuscators just have an option as described i in the issue.

**Comment by levno-710** [comment]
I am currently on vacation, so I cannot work on this, but I would be happy to accept a pull request, that removes the watermark

**Comment by wrefgtzweve** [comment]
Why was the watermark readded?

**Comment by levno-710** [comment]
Due to a feature request, although it is now another step, that can be disabled

**Comment by wrefgtzweve** [comment]
I don't think a watermark should be in the default script config, plenty of points where brought up here why it shouldn't be.
And this remark makes me fearful of using this project at all.
https://github.com/prometheus-lua/Prometheus/pull/102#issuecomment-1346579958
![image](https://user-images.githubusercontent.com/69946827/207651049-c607bdc1-c6e1-4396-8eee-8315679c4b67.png)

**Comment by levno-710** [comment]
This is not so that the watermark cannot be changed by the user of prometheus, but rather by someone that will try to change the watermark after obfuscation.

This would only be a valid use case, if you wanted to steal the script and claim it as your own.

The watermark can still be changed or disabled by the script owner when using prometheus.

**Comment by wrefgtzweve** [comment]
Ah yeah that makes a lot more sense, i read it as it'd intentionally break code if it you where to remove the prometheus watermark. Thank you for your response. I appreciate that you removed it from the default presets! It's a cool feature but i feel like it indeed isn't something that should be on by default. Having it error when the watermark is removed sounds like a neat feature if used in the right usecase!
