### ISSUE TITLE
[BUG] ENOBUFS

### ISSUE THREAD

**Issue by artificialai223** [levno-710/Prometheus#73]
Getting an ENOBUFS error with a 5,000 line lua script. LuaU, Medium.

**Comment by levno-710** [comment]
How much ram do you have?

> ENOBUFS means there is no sufficient memory available and the system(kernel) can not allocate any more.

**Comment by artificialai223** [comment]
I have 128GB of ram, I am using the API option and i believe the issue is the print()

**Comment by levno-710** [comment]
What print do you mean?

**Comment by levno-710** [comment]
I think this may be, because the Ast of your file is too big for lua.
Luajit for example can by default only handle 2GB of ram.

**Comment by levno-710** [comment]
It could also be the case, that the obfuscated code is too large to be printed
