### ISSUE TITLE
[BUG] File Size (Parsing Errors)

### ISSUE THREAD

**Issue by ImInTheICU** [levno-710/Prometheus#78]
**Describe the bug**
When uploading a 2mb file I got stuck on the Parsing Screen.

**Expected behavior**
To obfuscate the file.

**To Reproduce**
Upload a file 2mb in size.

**Screenshots**
![image](https://user-images.githubusercontent.com/111275373/185261449-0c1c1a88-28cf-4d60-b680-ddfa3457c2ad.png)

**Additional context**
Nope, just wish it worked with medium sized files.

**Comment by ImInTheICU** [comment]
(Update: Still on the parsing screen its now been 24 minutes)

**Comment by levno-710** [comment]
This is a know issue, and I am working on fixing this.
My parser (actually mostly the tokenizer) is really slow.

**Comment by ImInTheICU** [comment]
> This is a know issue, and I am working on fixing this. My parser (actually mostly the tokenizer) is really slow.

Also do you know when you will push a fix, were still waiting for the random strings mentioned in another ticket?
Im not sure what you would call this....
(Sorry if that come out rude, i dident mean it like that.)

**Comment by levno-710** [comment]
I am currently not abled to work on Prometheus a lot, because I am in an Internship where I have to work full time, but I try to adress these issues as fast as possible

**Comment by ImInTheICU** [comment]
> I am currently not abled to work on Prometheus a lot, because I am in an Internship where I have to work full time, but I try to adress these issues as fast as possible

That sucks,

**Comment by ImInTheICU** [comment]
> I am currently not abled to work on Prometheus a lot, because I am in an Internship where I have to work full time, but I try to adress these issues as fast as possible

Also do you think theres a way around this 500kb limit??

**Comment by levno-710** [comment]
The only way that I think would be possible, would be to rewrite the parser and tokenizer

**Comment by levno-710** [comment]
Or to split the entire file into multiple chunks that require each other

**Comment by ImInTheICU** [comment]
> Or to split the entire file into multiple chunks that require each other

That could work but its kinda cheap, rewriting the tokenizer and parser is needed, thanks!

**Comment by levno-710** [comment]
Closing this issue, due to #83 being the same
