### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shadowTW** [levno-710/Prometheus#80]
![image](https://user-images.githubusercontent.com/64441627/185415140-9dc428c7-3397-4932-aef0-df37e189ce6b.png)
![image](https://user-images.githubusercontent.com/64441627/185415197-9dd54e84-213c-4748-abde-51a379300e5f.png)

**Comment by ImInTheICU** [comment]
Odd, sadly levno doesn't work on this that match meaning its going to be awhile before a patch is released.

**Comment by levno-710** [comment]
I would really appreciate if you could try and find a simple example code, that can be used to reproduce this bug.

Otherwise it is almost impossible for me, to find the source of the bug and fix it

**Comment by levno-710** [comment]
Can you try to track down, in what line the error occurs.

For example by using print statements and seeing which ones are printed before the error?

**Comment by quanmanss11** [comment]
syn.protect_gui synapse function ?!!!!

**Comment by levno-710** [comment]
Could you test wether this bug has been fixed in Prometheus v0.2.5.

The update should have fixed this bug
