### ISSUE TITLE
attempt to call a nil value

### ISSUE THREAD

**Issue by WiiZARDD** [levno-710/Prometheus#88]
**Describe the bug**
`lua: .\src\prometheus\util.lua:254: attempt to call a nil value (global 'newproxy')
stack traceback:
        .\src\prometheus\util.lua:254: in function 'prometheus.util.readonly'
        .\src\prometheus.lua:31: in main chunk
        [C]: in function 'require'
        .\src\cli.lua:13: in main chunk
        [C]: in function 'require'
        .\cli.lua:12: in main chunk
        [C]: in function 'require'
        prometheus-main.lua:1: in main chunk
        [C]: in ?`

**Expected behavior**
this happens when I try running promethus-main.lua

**Comment by WiiZARDD** [comment]
Also getting

`lua: ./src\prometheus\util.lua:254: attempt to call a nil value (global 'newproxy')
stack traceback:
        ./src\prometheus\util.lua:254: in function 'prometheus.util.readonly'
        ./src\prometheus.lua:31: in main chunk
        [C]: in function 'require'
        ./src\cli.lua:13: in main chunk
        [C]: in function 'require'
        ./cli.lua:12: in main chunk
        [C]: in ?`
        
        when doing
`lua ./cli.lua --preset Strong ./test.lua`

**Comment by levno-710** [comment]
You're using Prometheus with an unsupported Lua Version
