### ISSUE TITLE
[BUG] Anti Beautifier

### ISSUE THREAD

**Issue by Brohammer5** [levno-710/Prometheus#94]
**Describe the bug**
You can still beautify the obfuscated codes when using other language beautifiers

**Expected behavior**
You shouldn't be able to Beautify code.

**To Reproduce**
1. Make obfuscated code with any preset
2. Go to. https://beautifier.io/

**Screenshots**

**Additional context**

**Comment by levno-710** [comment]
If you obfuscate using medium or strong preset, you won't be able to run the beautified script
