### ISSUE TITLE
[BUG] Glua can't be parse with --LuaU

### ISSUE THREAD

**Issue by bozoweed** [levno-710/Prometheus#97]
**Describe the bug**
←[0m←[31mPROMETHEUS: Lexing Error at Position 4:4, Unexpected char "!"!←[0m

the line is like 

if(!loaded)then print("not loaded")end

**Expected behavior**
should parse it or replace the excepted code

**To Reproduce**
if(!loaded)then print("not loaded")end
prometheus.exe --LuaU --preset Medium
(dowload from alpha lastest

If your problem is a non-working obfuscated file, please also include a minimal source code example, your config file as well as the output file that you got.

all is default value

**Screenshots**
![image](https://user-images.githubusercontent.com/11362992/202543290-96a2a613-000c-4d68-a0e4-1286383a31d3.png)

**Comment by levno-710** [comment]
This is, because LuaU is not GLua.

While Glua Support !, LuaU only supports the not keyword.
